language: ruby
sudo: false
cache: bundler
bundler_args: --without development
rvm:
  - ruby-head
  - ruby
  - jruby
  - 2.4.1
before_script: bundle update
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby
    - rvm: jruby-head
    - rvm: jruby
notifications:
  email: false
env:
  - CODECLIMATE_REPO_TOKEN=5eee8e8624962f963a52a1d2313dc7407e3b8006291e3704346c786642cc073b
